#pragma once
float mousex = 0;
float mousey = 0;
float playerx = 250;
float playery = 250;
float enemyRx = 750;
float enemyRy = 450;
float enemyGx = 775;
float enemyGy = 360;
float colliderGx = 258;
float colliderGy = 250;
float enemyBx = 725;
float enemyBy = 50;
int FEAR = 0;
int distanceG;
int distanceB;
int distanceR;
bool colorR = false;
bool colorG = false;
bool colorB = false;
bool bulletR = false;
bool redbullet = false;
bool greenbullet = false;
bool bluebullet = false;
bool bulletG = false;
bool bulletB = false;
float rot = 0;
float time = 180;
int bulletSpeed = 300;
int bulletAmountR = 0;
int Health;
int bulletAmountG = 0;
int bulletAmountB = -1;